language: node_js
node_js:
- '7'
- '8'
- 'lts/*'
- 'node'
before_script:
- gem install scss_lint
deploy:
  provider: npm
  email: nessthehero@gmail.com
  api_key:
    secure: iSXsx0lctUfxVvwxTdpcYlo/QLIDmky6zC3ZeE5Gi/XHFwDLidC4iM0rOpnTgcS83Wt+xkAZ9GwvKi5XpQARSspeaDnvwOQxUTCOeTSuYiepfDbuEtqSFdD6k85PH4EeqJpr0eeZ1Is1E1PT1pLDfLEG+AS/AeCqX1FIPGzG478=
  on:
    tags: true
    repo: BarkleyREI/brei-sass-boilerplate
